@x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJiYW9AZ21haWwuY29tIiwiaWF0IjoxNjY3NTQ4ODM0LCJleHAiOjE2Njc1NTYwMzR9.JLQez20rAaNymTNAG2UnCmEPKunkeqOU1OXe-NHOPNE

//Register
POST http://localhost:2003/register
Content-Type: application/json

{
    "full_name": "Diptya Bagus Sumantry", 
    "email": "basokokok@gmail.com", 
    "password": "abcd1234",
    "gender": "Male",
    "role": "2",
    "balance": "10000000"
}

//Login
###
POST http://localhost:2003/login
Content-Type: application/json

{
    "email": "bao@gmail.com", 
    "password": "abcd1234"
}

//Users
###
GET http://localhost:2003/users/get
x-access-token: {{x-access-token}}

###
PUT http://localhost:2003/users/update/1
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "full_name" : "Diptya ", 
    "email": "diptyaa@gmail.com", 
    "password": "abcd1234",
    "gender": "Male",
    "role": "1",
    "balance": "10000"   
}

###
DELETE http://localhost:2003/users/delete/1
x-access-token: {{x-access-token}}

//Category
###
POST http://localhost:2003/category/create
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "tipe": "Hobi dan Koleksi", 
    "sold_product_amount": 5
}

//Product
###
POST http://localhost:2003/product/create
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "title": "Susu Murni",
    "price": "10000",
    "stock": "10", 
    "CatagoryId": 2
}

###
GET http://localhost:2003/product/get
x-access-token: {{x-access-token}}

###
PUT http://localhost:2003/product/update/1
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "title": "Susu Sapi",
    "price": "10000",
    "stock": "20", 
    "CatagoryId": 1
}

###
DELETE http://localhost:2003/product/delete/1
x-access-token: {{x-access-token}}