@x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhc2Rhc2RAZ21haWwuY29tIiwiaWF0IjoxNjY3NzMyNTkwLCJleHAiOjE2Njc3Mzk3OTB9.NECEOkjCLNGLQs3aRD9v-G32nMA5wfJayB4xh4b3FZc
# @x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2Njc3MjMwMDEsImV4cCI6MTY2NzczMDIwMX0.-rxxvGXTzNHfYc6t_sy4yV052s7NrbvLbmUrR9azGTM
//Register
POST http://localhost:2003/register
Content-Type: application/json

{
    "full_name": "Nauval", 
    "email": "asdasd@gmail.com", 
    "password": "123456",
    "gender": "Male"
} 

//Login
###
POST http://localhost:2003/login
Content-Type: application/json

{
    "email": "asdasd@gmail.com", 
    "password": "123456"
}

//Users
###
GET http://localhost:2003/users/getLogin
x-access-token: {{x-access-token}}

###
GET http://localhost:2003/users/get
x-access-token: {{x-access-token}}

###
PUT http://localhost:2003/users/update
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "full_name" : "admin", 
    "email": "admin@gmail.com"   
}

###
DELETE http://localhost:2003/users/delete
x-access-token: {{x-access-token}}

###
PATCH http://localhost:2003/users/topup
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "balance" : 110000
}

//Category
###
POST http://localhost:2003/category/create
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "tipe": "asd"
}

###
GET http://localhost:2003/category/get
x-access-token: {{x-access-token}}

###
PATCH http://localhost:2003/category/update/2
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "tipe": "Hobii"
}

###
DELETE http://localhost:2003/category/delete/12
x-access-token: {{x-access-token}}

//Product
###
POST http://localhost:2003/product/create
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "title": "Susu Murni",
    "price": 10000,
    "stock": 10, 
    "CategoryId": 9
}

###
GET http://localhost:2003/product/get
x-access-token: {{x-access-token}}

###
PUT http://localhost:2003/product/update/2
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "title": "Susu Sapi",
    "price": 10000,
    "stock": 123
}

###
PATCH http://localhost:2003/product/patch/2
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "CategoryId": 9
}

###
DELETE http://localhost:2003/product/delete/6
x-access-token: {{x-access-token}}

//TransactionHistory
###
POST http://localhost:2003/transaction/create
Content-Type: application/json
x-access-token: {{x-access-token}}

{
    "ProductId": 4, 
    "quantity": 10
}

###
GET  http://localhost:2003/transaction/get/user
x-access-token: {{x-access-token}}

###
GET  http://localhost:2003/transaction/get/admin
x-access-token: {{x-access-token}}

###
GET   http://localhost:2003/transaction/2
x-access-token: {{x-access-token}}
